#!/bin/bash

old_brightness=""

get_brightness() {
    brightness=$(brightnessctl | awk '/Current brightness/ {gsub(/[\(\)%]/, "", $4); print $4}')
    echo "$brightness"
}

while true; do
    current_brightness=$(get_brightness)

    if [ "$current_brightness" != "$old_brightness" ]; then
        echo "$current_brightness"
        old_brightness="$current_brightness"
    fi
done

