#!/bin/bash

previous_volume=0

get_volume() {
    local volume=$(pactl list sinks | grep 'Volume:' | head -n 1 | awk '{print $5}' | tr -d '%')
    echo "$volume"
}

while true; do
    current_volume=$(get_volume)

    if [ "$current_volume" -ne "$previous_volume" ]; then
        echo "$current_volume"
        previous_volume="$current_volume"
    fi

done
