#!/bin/bash

exec playerctl metadata --follow -p spotifyd --format '{{artist}};{{title}};{{mpris:artUrl}};{{album}};{{position}};{{mpris:length}}' | \
   while read -r line; do

    artist=$(echo "$line" | awk -F ';' '{ print $1 }')
    title=$(echo "$line" | awk -F ';' '{ print $2 }')
    url=$(echo "$line" | awk -F ';' '{ print $3 }')
    album=$(echo "$line" | awk -F ';' '{ print $4 }')
    position=$(echo "$line" | awk -F ';' '{ print $5 }')
    length=$(echo "$line" | awk -F ';' '{ print $6 }')
    
    
    imageKey=$(basename "$url")
    imagePath=$HOME/.cache/spotify-images/$imageKey
    
    if ! [[ -e $imagePath ]]; then
     curl -fsLo $imagePath $url
    fi

    echo "{\"artist\":\"$artist\",\"title\":\"$title\",\"album\":\"$album\",\"image\":\"$imagePath\",\"position\":\"$position\",\"length\":\"$length\"}"
  done
